builders:
  modelith:
    import: "package:modelith_generator/builder.dart"
    builder_factories: ["modelith"]
    build_extensions: { ".dart": ["modelith.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
